- dds/Cargo.toml
- dds/src/implementation/rtps_udp_psm/udp_transport.rs
- dds_derive/Cargo.toml
- dds_derive/README.md
To support crates.io publication add package definitions to the manifest files.
> DDS-232 add info to manifest

- dds/src/implementation/data_representation_builtin_endpoints/discovered_reader_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/src/implementation/dds_impl/builtin_publisher.rs
- dds/src/implementation/dds_impl/builtin_subscriber.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/topic_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/implementation/rtps/types.rs
- dds/src/infrastructure/instance.rs
The EntityKind's like BUILT_IN_WRITER_WITH_KEY used to be constants of type u8. This was matching the idl but does not provide the benefits of type safety and readability. This PR replaces all the constants by an enum. For that the enum needs a custom serde::Serialize and Deserialize. The deserialization does at this moment not fail and falls back to 0.
> DDS-212 Replace EntityKind's by an enum

- dds/src/implementation/dds_impl/builtin_stateful_reader.rs
- dds/src/implementation/dds_impl/builtin_stateless_reader.rs
- dds/src/implementation/dds_impl/builtin_subscriber.rs
- dds/src/implementation/dds_impl/dcps_service.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/implementation/rtps/reader.rs
This PR removes the channel from the data reader and instead requires that the thread "asks" for state changes in order to trigger the listener.
> DDS-223 Rework trigerring of data reader listener

- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/builtin_stateless_writer.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/stateless_writer.rs
- dds/src/implementation/rtps/writer.rs
To be able to announce the deletion of a user-defined datawriter it is required that the built-in writer provides the dispose functionality. Right now it the functionality was copied in multiple places so this PR implements the functionality that is common to all writers in the underlying RTPS writer. This is a similar strategy to what was done in the RTPS reader.
> DDS-199 Move common writer methods to RTPS Writer

- dds/src/implementation/data_representation_builtin_endpoints/discovered_reader_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_topic_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/rtps/reader.rs
- dds/src/implementation/rtps/writer.rs
- dds/src/infrastructure/instance.rs
- dds/src/topic_definition/type_support.rs
- dds/tests/domain_participant_api.rs
- dds/tests/write_read_keyed_topic.rs
- dds_derive/src/lib.rs
- dds_derive/tests/test_dds_type_derive.rs
This PR creates a dedicated type for DdsSerializedKey and removes the endianness generic input from those methods. The new DdsSerializedKey is then placed on the wire using the regular CDR serialize and deserialize methods.
> DDS-206 Create a dedicated type for DdsSerializedKey

- dds/src/implementation/dds_impl/message_receiver.rs
- dds/src/implementation/rtps/messages/mod.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/stateless_writer.rs
- dds/src/implementation/rtps_udp_psm/mapping_basic_types.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/overall_structure.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/rtps_header.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/guid_prefix.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/protocol_version.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/vendor_id.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data_frag.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/heart_beat_frag.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/info_destination.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/info_reply.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/info_source.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/nack_frag.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/pad.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/submessage.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/submessage_header.rs
- dds/src/implementation/rtps_udp_psm/mapping_traits.rs
Some of the PSM types implemented MappingWrite and MappingWriteByteOrdered. This unnecessary double implementation is removed here. Likewise the Read implementations. The name of the traits are made more explicit.
> DDS-234 remove redundant mapping impls

- dds/src/implementation/dds_impl/topic_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/topic_definition/topic.rs
- dds/tests/discovery.rs
This PR extends the discovery mechanism to announce the data reader and data writer qos updates to the matched writers and readers, respectively.
> DDS-201 Announce data reader and data writer qos updates

- dds/src/domain/domain_participant_factory.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_reader_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/builtin_stateless_writer.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/message_receiver.rs
- dds/src/implementation/dds_impl/topic_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/rtps/messages/submessage_elements.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/stateless_writer.rs
- dds/src/implementation/rtps/types.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/overall_structure.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/rtps_header.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/count.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/guid_prefix.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/protocol_version.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/vendor_id.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/ack_nack.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/heart_beat.rs
- dds/src/infrastructure/instance.rs
Replace types of submessage elements by non representation types. So far the types as they were intended of the UDP mapping were used. This is unnecessary since the impl of the Mapping traits makes sure the submessage elements are mapped as specified.
> DDS-234 refactor submessage elements

- dds/src/implementation/rtps/reader.rs
- dds/src/implementation/rtps/writer.rs
- dds/src/infrastructure/qos.rs
- dds/src/infrastructure/qos_policy.rs
- dds/tests/write_read_unkeyed_topic.rs
The QoS was considered consistent in some combinations of unlimited length for max samples and max samples per instance. This was mostly due to the complicated comparisons in the if clauses. To solve this problem I have introduced a new Length type that makes the comparison more explicit.
> DDS-239 Fix QoS consistency bug

- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/rtps/reader.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/subscription/data_reader.rs
- dds/tests/data_reader_listener.rs
- dds/tests/write_read_unkeyed_topic.rs
Add listener trigger for Sample Rejected and Sample Lost. To do this triggering some additional information is return from the called to the RtpsReader data submessage processing. As part of this the triggering of the on_data_available has also been modified to not require the separate thread to look at the flag value.
> DDS-236 Add Sample Rejected and Sample Lost reader listeners

- .circleci/config.yml
- dds/src/implementation/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
This PR adds the capability of using the SPDP default locator when the discovered readers and writers do not report their own locator lists.
> DDS-247 Use SPDP default locators for matched readers and writers

- dds/src/implementation/data_representation_builtin_endpoints/discovered_reader_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/src/implementation/dds_impl/builtin_publisher.rs
- dds/src/implementation/dds_impl/builtin_subscriber.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/message_receiver.rs
- dds/src/implementation/dds_impl/topic_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/types.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/overall_structure.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/count.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/entityid.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/ack_nack.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/gap.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/heart_beat.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_types/submessage_or_builtin.rs
- dds/src/implementation/rtps_udp_psm/udp_transport.rs
The derive::Constructor was removed as well since it derived to non const fn. The later is however required by some constants.
> Make EntityKey new type

- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/tests/data_reader_listener.rs
This PR fixes the deadlock on the sample rejected test.
The reason why the deadlock is happening is because the drop being called on the DataReader available as part of the listener was actually attempting to delete the reader. This is not expected since the main thread should still have a weak reference to the data reader. However, because the main thread is waiting on the status condition and this status condition was triggered before running the listener this sometimes cause the object of the main thread to be already dropped by the time the listener finished executing. 
The fix to this problem is to trigger the status condition only after running the listener. This is also how it is described by the DDS standard in 2.2.4.6 Combination
> DDS-250 Fix deadlock on sample rejected test

- dds/src/domain/domain_participant.rs
- dds/src/domain/domain_participant_factory.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/topic_definition/topic.rs
- dds/tests/domain_participant_factory.rs
The topic object was not deleted when the object was going out of scope. This was preventing other objects from being deleted as well which also caused the disposal messages not to be sent. A test is added to explicitly verify that once going out of scope a participant can't be found in the factory anymore.
> DDS-254 Delete topic on drop

- dds/src/domain/domain_participant_factory.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/subscription/subscriber.rs
- dds/tests/subscriber_api.rs
Add default datareader QoS to subscriber and clean-up an old way of getting the parent participant.
> DDS-261 Add default datareader QoS to subscriber

- dds/src/domain/domain_participant_factory.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/tests/domain_participant_api.rs
- dds/tests/domain_participant_factory.rs
Add delete_contained_entities functionality and prevent the DomainParticipant from being deleted if it still contains any entity.
> DDS-264 Add delete_contained_entities functionality

- .circleci/config.yml
- dds/src/implementation/dds_impl/dcps_service.rs
- dds/tests/data_available_listeners.rs
- dds/tests/data_reader_listener.rs
- dds/tests/data_writer_listener.rs
- dds/tests/discovery.rs
- dds/tests/domain_participant_api.rs
- dds/tests/domain_participant_factory.rs
- dds/tests/domain_participant_factory_qos.rs
- dds/tests/domain_participant_listener.rs
- dds/tests/publisher_api.rs
- dds/tests/publisher_listener.rs
- dds/tests/subscriber_api.rs
- dds/tests/subscriber_listener.rs
- dds/tests/utils/domain_id_generator.rs
- dds/tests/utils/mod.rs
- dds/tests/write_read_keyed_topic.rs
- dds/tests/write_read_unkeyed_topic.rs
This PR allows the test suite to run in parallel with the default "cargo test" command. This is achieved by having a static domain_id generator that can be used to ensure that each test gets a unique domain id.
Running in parallel however didn't affect the overall performance of the tests given that a lot of time was spent in shutting down the tasks. To increase the performance the condvar are now all triggered when shutting down the tasks to make sure that the loops stop as fast as possible.
> DDS-267 Parallelize integration tests

- dds/src/implementation/dds_impl/builtin_stateful_reader.rs
- dds/src/implementation/dds_impl/builtin_stateless_reader.rs
- dds/src/implementation/dds_impl/builtin_subscriber.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/implementation/rtps/stateless_reader.rs
- dds/src/subscription/data_reader.rs
- dds/tests/builtin_readers.rs
This PR adds the possibility for the user to access the data stored in the built-in readers. To make that data available to the outside the internal access was replace from a take, which was consuming the data, into a read with a filter on unread samples. I have also decided to provide only the read API to the user and not the take. This is to prevent data from disappearing from the built-in readers. Therefore calling take on a built-in reader will result in an IllegalOperation error. 
To keep the test free of sleep usages, the status conditions is also added to the built-in reader. According to the standard (chapter 2.2.5) the user should be able to use listeners, conditions and wait-sets. These mechanisms still need to be extended but for now it seems enough to show the ability to …
> DDS-269 Access built-in reader data

- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data_frag.rs
Fix data-frag submessage. Add serialization and de-serialization test. 
Here is a Wireshark output for a data for id(u8) and value(Vec<u8;100000>) :
8045	\Device\NPF_Loopback		343.670031	192.168.1.5	192.168.1.5	RTPS	60120	7411	INFO_DST, INFO_TS, DATA_FRAG
8097	\Device\NPF_Loopback		343.671204	192.168.1.5	192.168.1.5	RTPS	40132	7411	INFO_DST, INFO_TS, DATA_FRAG
> DDS-277 Fix data frag submessage serialization and de-serialization

- dds/src/implementation/rtps/reader_proxy.rs
Use heartbeat machines to decouple the concern of counting and timing from the ReaderProxy. Also make the loop of the data_frags more explicit (do not use the enumeration anymore).
> DDS-281 Introduce heartbeat machine

- dds/src/implementation/dds_impl/builtin_stateful_reader.rs
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/tests/discovery.rs
- dds/tests/domain_participant_api.rs
This PR makes the participant remove other discovered participants after the lease duration period sent by SPDP is elapsed. The API function to ignore participant is also added.
> DDS-279 remove matched participant after lease

- dds/src/domain/domain_participant.rs
- dds/src/implementation/dds_impl/any_topic_listener.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/status_condition_impl.rs
- dds/src/implementation/dds_impl/topic_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/publication/data_writer.rs
- dds/src/publication/publisher.rs
- dds/src/subscription/subscriber.rs
- dds/src/topic_definition/topic.rs
- dds/tests/write_read_keyed_topic.rs
This PR adds the inconsistent topic detection. To enable testing the status condition is added to the Topic and other entities where it is missing.
> DDS-278 Add inconsistent topic detection and status condition

- dds/src/implementation/rtps/reader.rs
- dds/tests/write_read_keyed_topic.rs
This PR adds the Time-Based Filter qos policy functionality. By standard this applies to the reader samples only.
> DDS-286 Add time based filter qos policy

- dds/src/implementation/dds_impl/builtin_stateful_reader.rs
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/builtin_stateless_reader.rs
- dds/src/implementation/dds_impl/builtin_stateless_writer.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/infrastructure/time.rs
- dds/tests/write_read_keyed_topic.rs
This PR implement the behavior of Volatile and TransientLocal Durability on the reader side. This mostly involves implementing the wait_for_historical_data function.
The QoS of the built-in types are also adjusted to better reflect the table on page 140 of the DDS standard.
I also corrected some bugs with other condvar waits when implementing a similar one for this purpose. Those wrong wait times were probably just causing the while loop to run too often (lower performance) so they were not really serious or visible on the tests.
> DDS-283 Durability QoS policy on the reader side

- .circleci/config.yml
- dds/Cargo.toml
- dds/examples/hello_world_publisher.rs
- dds/tests/executables/publisher.rs
- dds/tests/executables/subscriber.rs
- dds_derive/src/lib.rs
Add multi-machine tests to allow testing for multiple subscribers to verify that multiple IPs are working. 
Note that the publisher needs to wait for the 2 subscribtions beeing matched. This is done using an infinite loop here. Ans implementation of that kind: 
```
let number_of_subscribers_to_find = 2;
for _ in 0..number_of_subscribers_to_find {
wait_set.wait(Duration::new(60, 0)).unwrap();
}
let number_of_matched_readers = writer.get_matched_subscriptions().unwrap().len();
// Or: let number_of_matched_readers = writer.get_publication_matched_status().unwrap().current_count;
// Or: let number_of_matched_readers = writer.get_publication_matched_status().unwrap().total_count;
assert_eq!(number_of_subscribers_to_find, number_of_matched_readers);
```
resulted mostly in only 1 matched reader. …
> DDS-268 Add multiple subscriber integration test

- .circleci/config.yml
- dds/tests/executables/publisher.rs
- dds/tests/write_read_keyed_topic.rs
Use a finite loop in the multi subscriber tests. 
Also make the transient_local_writer_reader_wait_for_historical_data test stable (due to a similar cause)
> DDS-268 Use get publication matched status for tests

- dds/src/implementation/dds_impl/data_writer_factory.rs
- dds/src/implementation/dds_impl/mod.rs
- dds/src/implementation/dds_impl/reader_factory.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/implementation/dds_impl/writer_factory.rs
- dds/tests/publisher_api.rs
- dds/tests/subscriber_api.rs
This PR fixes a bug in which different readers were not being assigned unique ID's. The fix involves moving the code that create the user defined reader and writer into a dedicated factory class which can be more easily unit tested.
> DDS-295 Fix reader factory bug

- Cargo.toml
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data_frag.rs
- dds/tests/write_read_keyed_topic.rs
- dds_derive/src/lib.rs
- idlgen/src/mappings/rust.rs
- idlgen/tests/examples/structs.rs
- shapes_demo/Cargo.toml
- shapes_demo/build.rs
- shapes_demo/src/ShapeType.idl
- shapes_demo/src/main.rs
- shapes_demo/src/shapes_type.rs
- shapes_demo/src/subscriber.rs
Add shapes demo skeleton. A subscriber bin is added for development purposes.
- Some Clippy warnings are fixed and some timeouts in the tests are increased.
- The key value macro for non copy types is fixed in the derive crate.
- The idl gen generates now Strings from size limited templates such as string<128> gets a String now.
> DDS-292 Add shapes demo

- dds/src/implementation/rtps/stateful_writer.rs
- dds/tests/write_read_keyed_topic.rs
This PR includes the usage of the durability QoS on the writer side to avoid new readers from receiving old samples.
> DDS-283 Use durability QoS for writer without matched readers

- .circleci/Dockerfile
- .circleci/config.yml
- .circleci/continue-config.yml
- dds/Cargo.toml
- interoperability_tests/Cargo.toml
- shapes_demo/Cargo.toml
- shapes_demo/src/main.rs
- shapes_demo/src/subscriber.rs
Add a GUI and the publishing of a Circle. The RTI shapes demo can subscribe to that Circle data.
The Rust version is increased to 1.65 since the added egui dependency needs Rust 1.65. An enforced earlier egui version (0.19.0) does depend only on Rust 1.62, however this failed in compiling the sysfont dependency. 
To make this work also the docker image for the interoperability test docker image needed an upgrade.
> DDS-292 Add publishing of circle

- dds/src/implementation/data_representation_inline_qos/parameter_id_values.rs
- dds/src/implementation/data_representation_inline_qos/types.rs
- dds/src/implementation/dds_impl/builtin_subscriber.rs
- dds/src/implementation/rtps/reader.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/stateless_reader.rs
- dds/src/implementation/rtps/types.rs
- dds/src/implementation/rtps/writer.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/overall_structure.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/parameter_list.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data.rs
This PR fixes a set of bugs preventing the Shapes demo from disposing the subscriber. The issues fixed are:
1. Wrong interpretation of the length in the sentinel parameter
2. Usage of KeyHash when the key is not explicitly transmitted in the Data submessage
3. SPDP stateless reader absorbing all the received messages with ENTITYID_UNKNOWN
> DDS-297 Fix shapes dispose subscriber bugs

- dds/src/implementation/dds_impl/participant_discovery.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/rtps/history_cache.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/types.rs
- dds/tests/domain_participant_factory.rs
- dds/tests/write_read_samples.rs
This PR adds the usage of the reader durability for the writer to decide which changes are relevant to send to each matched reader.
> DDS-283 Use durability of matched reader

- dds/src/domain/domain_participant_factory.rs
- dds/src/implementation/dds_impl/dcps_service.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/topic_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/publication/data_writer.rs
- dds/src/publication/publisher.rs
- dds/src/subscription/data_reader.rs
- dds/src/subscription/subscriber.rs
- dds/src/topic_definition/topic.rs
- dds/tests/discovery.rs
- dds/tests/write_read_samples.rs
In the current architecture the implementation objects are too big which is hindering the implementation of the missing QoS functionality. As a way to reduce this complexity, this change reduces (but does not yet totally eliminate) dependencies on the parent objects.
> Refactor: Reduce parent dependencies on object implementations

- .gitignore
- idlgen/src/idl/mod.rs
- idlgen/src/lib.rs
- idlgen/src/mappings/rust.rs
- idlgen/src/syntax/constants.rs
- idlgen/tests/examples.rs
- interoperability_tests/Cargo.toml
- interoperability_tests/build.rs
- shapes_demo/Cargo.toml
- shapes_demo/build.rs
- shapes_demo/src/shapes_type.rs
Add an interface to the IDL parser such that the implementation details (e.g. Pest library) can be hidden away from the user and don't need to be imported throughout all the user crates.
> DDS-300 Productize IDL parser

- dds/src/domain/domain_participant.rs
- dds/src/domain/domain_participant_listener.rs
- dds/src/implementation/dds_impl/builtin_subscriber.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/message_receiver.rs
- dds/src/implementation/dds_impl/mod.rs
- dds/src/implementation/dds_impl/status_listener.rs
- dds/src/implementation/dds_impl/topic_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/publication/data_writer.rs
- dds/src/publication/publisher.rs
- dds/src/subscription/data_reader.rs
- dds/src/subscription/subscriber.rs
- dds/src/topic_definition/topic.rs
- dds/tests/domain_participant_factory.rs
- dds/tests/listeners.rs
This PR adds calls to the listeners of the parent objects. This is done by grouping the Listener+Mask into a new object called StatusListener and passing this object down the tree to enable calling the necessary functions. This has the advantage of reducing the dependency to the entire parent object. A couple of missing functions from the DomainParticipantListener trait were also added.
> DDS-303 Add calls to listener function of parent objects

- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/dcps_service.rs
- dds/src/implementation/dds_impl/iterators.rs
- dds/src/implementation/dds_impl/mod.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/rtps/history_cache.rs
- dds/src/implementation/rtps/reader_locator.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/stateless_writer.rs
- dds/src/implementation/rtps/writer.rs
- dds/tests/domain_participant_api.rs
This refactor makes the message sending on the stateful writer become an external behavior rather than a member function of a class. This is a step to reduce the scope of the locks and reduce the chances of getting into deadlock situations.
> DDS-310 Refactor writer message sending to reduce lock usage

- dds/src/implementation/utils/map.rs
- dds/src/implementation/utils/mod.rs
This PR introduces a new map type (still unused except for tests) which can accommodate the object storage and associated values as a preliminary step for the upcoming refactoring.
> DDS-320 Create map type

- dds/src/dds/domain/dcps_service.rs
- dds/src/dds/domain/domain_participant.rs
- dds/src/dds/domain/domain_participant_factory.rs
- dds/src/dds/subscription/data_reader.rs
- dds/src/dds/subscription/subscriber.rs
- dds/src/implementation/dds_impl/dds_data_reader.rs
- dds/src/implementation/dds_impl/dds_domain_participant.rs
- dds/src/implementation/dds_impl/dds_subscriber.rs
- dds/src/implementation/dds_impl/message_receiver.rs
- dds/src/implementation/dds_impl/node_builtin_data_reader_stateful.rs
- dds/src/implementation/dds_impl/node_builtin_data_reader_stateless.rs
- dds/src/implementation/dds_impl/node_builtin_subscriber.rs
- dds/src/implementation/dds_impl/node_domain_participant.rs
- dds/src/implementation/dds_impl/node_kind.rs
- dds/src/implementation/dds_impl/node_user_defined_data_reader.rs
- dds/src/implementation/dds_impl/node_user_defined_subscriber.rs
This PR replaces the usage of the DdsShared by getting the object from the static factory on the reader side.
> DDS-322 Use static type for reader operations

- dds/src/dds/domain/domain_participant.rs
- dds/src/implementation/dds_impl/dds_domain_participant.rs
- dds/src/implementation/dds_impl/node_domain_participant.rs
- dds/tests/discovery.rs
Dropping the topics in the find discovered topic test caused the parent participant to be deleted. Hence keeping the topics in a list prevented this.
> DDS-324 Fix find topic

- dds/README.md
- dds/benches/benchmark.rs
- dds/examples/best_effort_publisher.rs
- dds/examples/best_effort_subscriber.rs
- dds/examples/hello_world_publisher.rs
- dds/examples/hello_world_subscriber.rs
- dds/src/dds/subscription/subscriber.rs
- dds/src/dds/topic_definition/type_support.rs
- dds/src/lib.rs
- dds/tests/discovery.rs
- dds/tests/domain_participant_api.rs
- dds/tests/domain_participant_factory.rs
- dds/tests/listeners.rs
- dds/tests/publisher_api.rs
- dds/tests/subscriber_api.rs
- dds/tests/write_read_samples.rs
- dds_derive/README.md
- dds_derive/src/lib.rs
- dds_derive/tests/test_dds_type_derive.rs
- interoperability_tests/Cargo.toml
- interoperability_tests/build.rs
- interoperability_tests/dust_dds_big_data_publisher.rs
- interoperability_tests/dust_dds_big_data_subscriber.rs
- interoperability_tests/dust_dds_publisher.rs
- interoperability_tests/dust_dds_subscriber.rs
- interoperability_tests/publisher_multi_machine.rs
- interoperability_tests/subscriber_multi_machine.rs
The DdsSerde marker trait could be used to mark DdsType that are meant to be serialized with CDR_LE encapsulation. This distinction can now be done directly within the  DdsType trait. As such the creation of serializable types is easier to explain.
This requires the dust-dds-gen crate to be updated as well. Since the dev dependencies of some of the crates here make use of dust-dds-gen this should be published first: https://github.com/s2e-systems/dust-dds-gen/pull/2
> DDS-308 Remove DdsSerde trait

- dds/src/dds/domain/domain_participant.rs
- dds/src/dds/domain/domain_participant_factory.rs
- dds/src/implementation/behavior/domain_participant.rs
- dds/src/implementation/dds/dds_domain_participant.rs
This PR replaces the runtime per participant by a static runtime that is initialized at the beginning of the program. This ensures a consistent number of threads used throughout the execution and a "fair" distribution of work between the participants. On top of that the main lock is replaced by a tokio RwLock which can be awaited on read and write. This still doesn't solve the biggest issues with the lock contention but it is a step towards having a different (e.g. actor based) system
> DDS-308 Use global runtime

- dds/src/dds/domain/domain_participant.rs
- dds/src/implementation/dds/dds_data_reader.rs
- dds/src/implementation/dds/dds_data_writer.rs
- dds/src/implementation/dds/dds_subscriber.rs
- dds/src/implementation/dds/message_receiver.rs
- dds/src/implementation/rtps/history_cache.rs
- dds/src/implementation/rtps/messages/mod.rs
- dds/src/implementation/rtps/messages/submessages.rs
- dds/src/implementation/rtps/reader.rs
- dds/src/implementation/rtps/reader_locator.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/stateless_reader.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/overall_structure.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/serialized_payload.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/ack_nack.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data_frag.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/gap.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/heart_beat.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/heart_beat_frag.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/info_destination.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/info_reply.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/info_source.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/info_timestamp.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/nack_frag.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/pad.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/submessage_header.rs
Make fields of Read Submessages private. This should stabilize the usage of the messages throughout the code.
> DDS-328 Use u8 as rep invariant for rtps message read

- dds/benches/benchmark.rs
- dds/src/implementation/rtps/writer_proxy.rs
Replace the Vec<> of received samples on reader proxy by a sequence number to improve performance
> Replace vec by seq number to improve performance

- dds/src/dds/domain/domain_participant.rs
- dds/src/dds/domain/domain_participant_factory.rs
- dds/src/dds/publication/data_writer.rs
- dds/src/dds/publication/publisher.rs
- dds/src/dds/subscription/subscriber.rs
- dds/src/implementation/dds/dds_data_reader.rs
- dds/src/implementation/dds/dds_data_writer.rs
- dds/src/implementation/dds/dds_domain_participant.rs
- dds/src/implementation/dds/dds_domain_participant_factory.rs
- dds/src/implementation/dds/dds_publisher.rs
- dds/src/implementation/dds/dds_subscriber.rs
- dds/src/implementation/utils/actor.rs
Tokio channels notify the receiver every time a sender is dropped. For the actor framework this means that cloning senders for a short duration can have an impact on performance since the receiver side will get unblocked and the runtime has to process potentially many requests. To minimize the impact on performance actor addresses are only cloned where needed and otherwise a reference is used.
> Return actor address reference and clone where necessary

- dds/Cargo.toml
- dds/src/dds/domain/domain_participant_factory.rs
- dds/src/implementation/rtps_udp_psm/udp_transport.rs
- dds/tests/write_read_samples.rs
The Ifcfg doesn't allow cross-compilation from windows to raspberry pi because of the way its build.rs script is used. To enable cross compilation this crate is replaced by network_interfaces
> Replace Ifcfg crate to enable cross compilation

- dds/src/implementation/rtps/messages/overall_structure.rs
- dds/src/implementation/rtps/messages/submessage_elements.rs
- dds/src/implementation/rtps/messages/submessages/ack_nack.rs
- dds/src/implementation/rtps/messages/submessages/data.rs
- dds/src/implementation/rtps/messages/submessages/data_frag.rs
- dds/src/implementation/rtps/messages/submessages/gap.rs
- dds/src/implementation/rtps/messages/submessages/heartbeat.rs
- dds/src/implementation/rtps/messages/submessages/heartbeat_frag.rs
- dds/src/implementation/rtps/messages/submessages/info_destination.rs
- dds/src/implementation/rtps/messages/submessages/info_reply.rs
- dds/src/implementation/rtps/messages/submessages/info_source.rs
- dds/src/implementation/rtps/messages/submessages/info_timestamp.rs
- dds/src/implementation/rtps/messages/submessages/nack_frag.rs
- dds/src/implementation/rtps/messages/submessages/pad.rs
- dds/src/implementation/rtps/messages/types.rs
- dds/src/implementation/rtps/types.rs
The big Endianness of the RTPS message serialization was not tested and is likely to be not used in the future, This PR removes the endianness switch from the message serialization (WriteBytes trait)
> DDS-341 Remove endianess from serialization

- dds/src/implementation/rtps/writer_history_cache.rs
- dds/tests/write_read_samples.rs
Fix an issue in which the history Qos on the writer side was not correctly used resulting in the wrong samples being sent to the reader.
> Issue #167 - Fix wrong behavior on History Writer QoS

- .circleci/continue-config.yml
- dds/Cargo.toml
- dds/benches/benchmark.rs
- dds/src/dds/domain/domain_participant.rs
- dds/src/dds/domain/domain_participant_factory.rs
- dds/src/dds/publication/data_writer.rs
- dds/src/dds/publication/publisher.rs
- dds/src/dds/subscription/subscriber.rs
- dds/src/implementation/dds/dds_data_reader.rs
- dds/src/implementation/dds/dds_data_reader_listener.rs
- dds/src/implementation/dds/dds_data_writer.rs
- dds/src/implementation/dds/dds_data_writer_listener.rs
- dds/src/implementation/dds/dds_domain_participant.rs
- dds/src/implementation/dds/dds_domain_participant_factory.rs
- dds/src/implementation/dds/dds_domain_participant_listener.rs
- dds/src/implementation/dds/dds_publisher.rs
- dds/src/implementation/dds/dds_publisher_listener.rs
- dds/src/implementation/dds/dds_subscriber.rs
- dds/src/implementation/dds/dds_subscriber_listener.rs
- dds/src/implementation/dds/dds_topic.rs
- dds/src/implementation/dds_actor/data_reader.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/implementation/rtps_udp_psm/udp_transport.rs
- dds/src/implementation/utils/actor.rs
- dds/tests/write_read_samples.rs
Send a Gap message when a reader joins after many samples have been written to the writer. This is a typical scenario for example when have two running shapes demo and was missing functionality up to this point. During the implementation we noticed some low performance issues when receiving a lot of messages on the wire so the actor tasks were modified to be non-blocking.
> DDS-280 Ack mechanism on many irrelevant samples

- dds/src/implementation/utils/actor.rs
- dds/tests/tokio_runtime.rs
This change enabled DustDDS to run within a Tokio runtime. An additional test is added to verify this since the functionality is used by clients of the library.
> #173 Enable using DustDDS within tokio context

- dds/src/dds/domain/domain_participant.rs
- dds/src/dds/domain/domain_participant_factory.rs
- dds/src/dds/publication/data_writer.rs
- dds/src/dds/publication/publisher.rs
- dds/src/dds/subscription/data_reader.rs
- dds/src/dds/subscription/subscriber.rs
- dds/src/dds/topic_definition/topic.rs
- dds/src/implementation/dds/dds_data_reader.rs
- dds/src/implementation/dds/dds_data_writer.rs
- dds/src/implementation/dds/dds_domain_participant.rs
- dds/src/implementation/dds/dds_domain_participant_factory.rs
- dds/src/implementation/dds/dds_publisher.rs
- dds/src/implementation/dds/dds_subscriber.rs
- dds/src/implementation/dds/dds_topic.rs
- dds/src/implementation/rtps/messages/overall_structure.rs
- dds/src/implementation/rtps/messages/submessage_elements.rs
- dds/src/implementation/rtps/messages/submessages/ack_nack.rs
- dds/src/implementation/rtps/messages/submessages/data.rs
- dds/src/implementation/rtps/messages/submessages/data_frag.rs
- dds/src/implementation/rtps/messages/submessages/gap.rs
- dds/src/implementation/rtps/messages/submessages/heartbeat.rs
- dds/src/implementation/rtps/messages/submessages/heartbeat_frag.rs
- dds/src/implementation/rtps/messages/submessages/info_reply.rs
- dds/src/implementation/rtps/messages/submessages/info_source.rs
- dds/src/implementation/rtps/messages/submessages/nack_frag.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/types.rs
- dds/src/implementation/rtps/writer.rs
- dds/src/implementation/rtps/writer_history_cache.rs
- dds/src/implementation/utils/actor.rs
As a first step to fix #176 this PR refactors the steps of the discovery by moving the different parts into the class where the different responsibilities are handled. In brief, the DomainParticipant is now responsible for checking whether discovered readers and writers are ignored or not; the publisher/subscriber checks for the partition match; and the data reader/writer checks whether the discovered entities are matches and compatible. Originally all this was done in methods in the top level participant factory.
Bringing the code into the inner modules resulted in some unused functions now being reported as warnings. I prepended an _ to the unused RTPS methods instead of deleting since they are standard defined. The enums with unused variants are marked to allow dead code.
> 176 Discovery steps refactor

- dds/src/implementation/dds/dds_domain_participant.rs
- interoperability_tests/dust_dds_subscriber.rs
- interoperability_tests/publisher_multi_machine.rs
This PR adds the capability of discovering the topics directly from the discovery of readers and writers. This is particularly important for interoperability with implementations that do no have a Topics announcer and when not wanting to create local topics.
> 176 Discover topics from reader and writer

- dds/src/dds/domain/domain_participant.rs
- dds/src/dds/domain/domain_participant_factory.rs
- dds/src/dds/publication/data_writer.rs
- dds/src/dds/publication/publisher.rs
- dds/src/dds/subscription/data_reader.rs
- dds/src/dds/subscription/subscriber.rs
- dds/src/dds/topic_definition/topic.rs
- dds/src/implementation/dds/any_data_reader_listener.rs
- dds/src/implementation/dds/any_data_writer_listener.rs
- dds/src/implementation/dds/dds_domain_participant.rs
- dds/tests/listeners.rs
This PR removes the Sync trait bound which is a leftover from a previous DustDDS architecture implementation is not anymore necessary.
> 186 remove sync bound

- dds/src/cdr/deserialize.rs
- dds/src/cdr/deserializer.rs
- dds/src/cdr/parameter_list_deserialize.rs
- dds/src/cdr/parameter_list_deserializer.rs
- dds/src/cdr/parameter_list_serialize.rs
- dds/src/cdr/parameter_list_serializer.rs
- dds/src/cdr/serialize.rs
- dds/src/cdr/serializer.rs
- dds/src/dds/infrastructure/qos_policy.rs
- dds/src/dds/infrastructure/time.rs
- dds/src/dds/topic_definition/type_support.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds_derive/src/derive/cdr_deserialize.rs
- dds_derive/src/derive/cdr_serialize.rs
- dds_derive/src/derive/dds_key.rs
- dds_derive/src/derive/dds_serialize_data.rs
- dds_derive/src/derive/parameter_list.rs
Replace the concrete Serializer/Deserializer types on the Serialize/Deserialize methods by generic types. This is done to hide away the concrete type implementation and reduce the likelihood of breaking the API due to these type changes
> DDS-361 Replace Serializer/Deserializer concrete types by traits

- dds/src/dds/domain/domain_participant_factory.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/src/implementation/actors/subscriber_actor.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/implementation/rtps_udp_psm/udp_transport.rs
Using Valgrind DHAT we have observed that there are many heap allocations on send_message which are immediately thrown away. This happens because the message was send to the UdpTransportWrite actor via actor mail which allocates a box which is immediately used and discarded. This particular allocation is very large because the message buffer was sent inside it. To improve this the UdpTransportWrite is passed around as Arc instead of an actor.
> Performance: Replace UdpTransportWrite actor by an Arc to avoid allocations

- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/rtps/messages/overall_structure.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/implementation/rtps_udp_psm/udp_transport.rs
Remove more memory allocations cause by unnecessary .await calls.
Replace the list of irrelevant changes by marking them as received which eliminates the need to keep allocating an ever growing Vec and conforms better to the RTPS standard which states that on irrelevant message received the state goes to received.
> Performance: Remove more memory allocations

- dds/src/dds/configuration.rs
- dds/src/dds/domain/domain_participant_factory.rs
Add the possibility to set the receive buffer size to the DustDdsConfiguration. This is useful when sending large amounts of data with many fragments in which some of the data could be lost if the buffer is not big enough.
> DDS-362 Add receive buffer size to configuration

- dds/Cargo.toml
- dds/src/dds/builtin_topics.rs
- dds/src/dds/publication/publisher.rs
- dds/src/dds/subscription/subscriber.rs
- dds/src/dds/topic_definition/type_support.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_reader_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/parameter_id_values.rs
- dds_derive/Cargo.toml
- dds_derive/src/derive/dds_type_xml.rs
- dds_derive/src/derive/mod.rs
- dds_derive/src/lib.rs
- dds_gen/Cargo.toml
Add DDS XML type representation to the custom types and transmit that information with the reader and writer discovery data using a vendor specific parameter.
> Add DDS XML type representation

- dds/src/implementation/actors/data_reader_actor.rs
- dds/tests/write_read_samples.rs
There is a bug in which the same sample is received multiple times and this is noticed on calling the take function.
We tracked the problem to the usage of the stateless reader.
> Bugfix: Multiple samples received on take

- dds/Cargo.toml
This simple change removes an unused dependency from DustDDS
> Remove unused dependency

- .circleci/Dockerfile
- .circleci/continue-config.yml
- Cargo.toml
- dds/Cargo.toml
- dds/src/dds/domain/domain_participant.rs
- dds/src/dds/domain/domain_participant_factory.rs
- dds/src/dds/publication/data_writer.rs
- dds/src/dds/publication/publisher.rs
- dds/src/dds/subscription/data_reader.rs
- dds/src/dds/subscription/subscriber.rs
- dds/src/dds/topic_definition/topic.rs
- dds/src/implementation/actors/any_data_reader_listener.rs
- dds/src/implementation/actors/any_data_writer_listener.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_reader_listener_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/data_writer_listener_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/domain_participant_factory_actor.rs
- dds/src/implementation/actors/domain_participant_listener_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/src/implementation/actors/publisher_listener_actor.rs
- dds/src/implementation/actors/subscriber_actor.rs
- dds/src/implementation/actors/subscriber_listener_actor.rs
- dds/src/implementation/actors/topic_actor.rs
- dds/src/implementation/utils/actor.rs
- dds/tests/publisher_api.rs
- dds/tests/subscriber_api.rs
Remove the dependency on lazy_static. To achieve this each of the entities has to get a handle to the runtime to allow spawning tasks and actors. Even though it is more verbose I believe this makes the actual dependency tree clearer and could be beneficial if the architecture changes to have a runtime per participant instead of a single runtime for the whole system.
> Remove lazy_static dependency

- dds/src/dds/domain/domain_participant.rs
- dds/src/dds/publication/data_writer.rs
- dds/src/dds/publication/publisher.rs
- dds/src/dds/subscription/data_reader.rs
- dds/src/dds/subscription/subscriber.rs
- dds/src/dds/topic_definition/type_support.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/src/implementation/actors/subscriber_actor.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_reader_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_topic_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/tests/write_read_special_types.rs
This PR puts back the feature of sending the type XML in the discovery process using the new TypeSupport trait.
> Re-enable XML information on type discovery

- dds/src/dds/infrastructure/qos.rs
- dds/src/dds_async/data_reader.rs
- dds/src/dds_async/data_writer.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/tests/discovery.rs
Some tests were failing because the discovery was only triggered on the SPDP regular interval of 5 seconds. This made some tests with a timeout of 5 seconds flaky. This change triggers a message sending whenever any discovery event takes place.
> Trigger message sending on any discovery action

- dds/src/dds/domain/domain_participant.rs
- dds/src/dds_async/domain_participant.rs
- dds/src/dds_async/domain_participant_factory.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_factory_actor.rs
- dds/src/implementation/actors/subscriber_actor.rs
- dds/tests/domain_participant_api.rs
Make get_builtin_subscriber method not fallible. An additional clean-up is done to use the new not fallible methods to get the status condition to reduce function arguments and the clippy allow is removed where not necessary.
> Make get_builtin_subscriber infallible

- dds/Cargo.toml
- dds/src/implementation/actors/domain_participant_factory_actor.rs
- dds_derive/Cargo.toml
- dds_gen/Cargo.toml
On some platforms the network interface MAC address cannot be retrieved and would make DustDDS panic. This happens for example on an Android emulator. As such the IP is used.
> Use IP address for the host ID part of the GUID

- dds/src/implementation/actors/domain_participant_factory_actor.rs
- dds/src/implementation/rtps/types.rs
Join the multicast group by using all the IP address of the interfaces in the machine. This prevents windows from not directing the discovery when using shapes demos of different vendors in the same machine.
> Add interface list to join multicast group

- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/subscriber_actor.rs
- dds/src/implementation/rtps/message_receiver.rs
- dds/src/implementation/rtps/messages/types.rs
- dds/src/implementation/rtps/reader_history_cache.rs
- dds/src/implementation/rtps/writer.rs
- dds/src/implementation/rtps/writer_history_cache.rs
RTPS Timestamp messages were being sent with nanoseconds in the fraction field whereas the RTPS standard requires this value to be a fraction scaled in 2^32. This change fixes that inconsistency which was visible when communicating with other implementations.
> Fix RTPS time message inconsistency with standard

- .circleci/continue-config.yml
- dds/src/dds_async/data_reader_listener.rs
- dds/src/dds_async/data_writer_listener.rs
- dds/src/dds_async/domain_participant_listener.rs
- dds/src/dds_async/publisher_listener.rs
- dds/src/dds_async/subscriber_listener.rs
- dds/src/dds_async/topic_listener.rs
- dds/src/implementation/utils/sync_listener.rs
This change add a new stage to keep track of compilation times. It also replaces the default trait implementation by a immediately ready future.
> Add stage with compilation times

- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/rtps/messages/overall_structure.rs
- dds/src/implementation/rtps/messages/submessages/data.rs
- dds/src/implementation/rtps/messages/submessages/data_frag.rs
- dds/src/implementation/rtps/messages/submessages/pad.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/writer_history_cache.rs
- dds/src/implementation/rtps/writer_proxy.rs
The RtpsSubmessageKind enum required a replicative implementation of WriteIntoBytes for that enum. The performance seems not harmed (or slightly better). As a result all <Submessage>Read and <Submessage>Write are now the same and could merged, allowing for less code and lib space. Also no lifetime is necessary any more for and submessage, since the Data and InlineQos can be nowadays simply cloned because of the ArcSlice
> Replace RtpsSubmessageKind by Boxes

- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/rtps/messages/overall_structure.rs
- dds/src/implementation/rtps/messages/submessages/ack_nack.rs
- dds/src/implementation/rtps/messages/submessages/data.rs
- dds/src/implementation/rtps/messages/submessages/data_frag.rs
- dds/src/implementation/rtps/messages/submessages/gap.rs
- dds/src/implementation/rtps/messages/submessages/heartbeat.rs
- dds/src/implementation/rtps/messages/submessages/heartbeat_frag.rs
- dds/src/implementation/rtps/messages/submessages/info_destination.rs
- dds/src/implementation/rtps/messages/submessages/info_reply.rs
- dds/src/implementation/rtps/messages/submessages/info_source.rs
- dds/src/implementation/rtps/messages/submessages/info_timestamp.rs
- dds/src/implementation/rtps/messages/submessages/nack_frag.rs
- dds/src/implementation/rtps/messages/submessages/pad.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/writer_history_cache.rs
- dds/src/implementation/rtps/writer_proxy.rs
Since the rep invariant of the submessage read and write are the same: merge the two types.
> Merge submessage read and write

- dds/src/dds_async/data_reader.rs
- dds/src/dds_async/data_writer.rs
- dds/src/dds_async/publisher.rs
- dds/src/dds_async/subscriber.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/src/implementation/actors/subscriber_actor.rs
- dds/tests/listeners.rs
- dds/tests/write_read_samples.rs
Send pending writer messages before delete. This allows disposing and unregistering samples and immediately deleting the datawriter
> Send pending writer messages before delete

- dds/src/dds_async/condition.rs
- dds/src/dds_async/data_reader.rs
- dds/src/dds_async/data_writer.rs
- dds/src/dds_async/domain_participant.rs
- dds/src/dds_async/domain_participant_factory.rs
- dds/src/dds_async/publisher.rs
- dds/src/dds_async/subscriber.rs
- dds/src/dds_async/topic.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/domain_participant_factory_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/src/implementation/actors/topic_actor.rs
- dds/src/implementation/utils/actor.rs
- dds_derive/src/lib.rs
This change removes the methods from the ActorAddress object and instead provides the upgrade() method that must called before hand to get the actual Actor object. This reduces the amount of code generated and gets rid of the not so understandable ?? constructs. In terms of behavior this is no different than before since the same operation was done behind-the-scenes. The downside is that it is more verbose on the usage.
> Remove methods from actor address

- dds/src/dds/configuration.rs
- dds/src/dds_async/domain_participant.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/domain_participant_factory_actor.rs
This PR adds a configuration possibility for the participant announcement interval. To achieve this the announcement task is moved to the top level and a method to announce the participant is created. As a side-effect this simplifies the code structure and the enable function implementation.
> Add configuration for the participant announcement time

- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/domain_participant_factory_actor.rs
- dds/src/rtps/participant.rs
This is an internal refactor which add the possibility of setting locator list after the construction of the domain participant. This allows opening the sockets later which simplifies the code flow. It also opens the option for the future of having dynamic network configuration.
> Refactor: Set participant locator lists after construction

- dds/src/implementation/actors/domain_participant_factory_actor.rs
- dds/src/rtps/error.rs
- dds_gen/src/parser/mod.rs
For systems where there is only a loopback interface the discovery would not happen since the loopback device was filtered out. Here this restriction is removed.
> Remove loopback filter

- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/domain_participant_factory_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/src/implementation/actors/subscriber_actor.rs
- dds/src/rtps/message_receiver.rs
- dds/src/rtps/messages/overall_structure.rs
- dds/src/rtps/messages/submessage_elements.rs
- dds/src/rtps/messages/submessages/ack_nack.rs
- dds/src/rtps/messages/submessages/data.rs
- dds/src/rtps/messages/submessages/data_frag.rs
- dds/src/rtps/messages/submessages/gap.rs
- dds/src/rtps/messages/submessages/heartbeat.rs
- dds/src/rtps/messages/submessages/heartbeat_frag.rs
- dds/src/rtps/messages/submessages/nack_frag.rs
- dds/src/rtps/writer_proxy.rs
- dds/tests/reliability_tests.rs
- fuzz/fuzz_targets/fuzz_data_frag_submessage.rs
- fuzz/fuzz_targets/fuzz_data_submessage.rs
Replace the strategy of allocating a new buffer in an Arc on every reception by re-using the same Box slice for receiving all data and cloning the parts that are necessary (e.g. parameter list and cache changes).
> Performance optimization: Reuse memory for data reception

- dds/src/rtps/messages/overall_structure.rs
- dds/src/rtps/messages/submessage_elements.rs
- dds/src/rtps/messages/submessages/ack_nack.rs
- dds/src/rtps/messages/submessages/data.rs
- dds/src/rtps/messages/submessages/data_frag.rs
- dds/src/rtps/messages/submessages/gap.rs
- dds/src/rtps/messages/submessages/heartbeat.rs
- dds/src/rtps/messages/submessages/heartbeat_frag.rs
- dds/src/rtps/messages/submessages/info_destination.rs
- dds/src/rtps/messages/submessages/info_reply.rs
- dds/src/rtps/messages/submessages/info_source.rs
- dds/src/rtps/messages/submessages/info_timestamp.rs
- dds/src/rtps/messages/submessages/nack_frag.rs
- dds/src/rtps/messages/submessages/pad.rs
- dds/src/rtps/messages/types.rs
- dds/src/rtps/types.rs
Serialize the RTPS Message into a Vec instead of a stack allocated array. This avoids having to initialize the whole array and saves a re-allocation when moving the contents into an Arc.
> Performance optimization: Use Cursor for serializing RTPS messages

- dds/src/dds_async/condition.rs
- dds/src/dds_async/data_reader.rs
- dds/src/dds_async/data_writer.rs
- dds/src/dds_async/domain_participant.rs
- dds/src/dds_async/domain_participant_factory.rs
- dds/src/dds_async/publisher.rs
- dds/src/dds_async/subscriber.rs
- dds/src/dds_async/topic.rs
- dds/src/implementation/actor.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/domain_participant_factory_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/src/implementation/actors/subscriber_actor.rs
- dds/src/implementation/actors/topic_actor.rs
- dds/src/rtps/writer_proxy.rs
Replace actor channel by unbounded channel to remove the await on the message sending. This makes the code simpler and more performant. For our system this is not problematic since most operations require waiting for a reply so there is little chance that actor buffers will be growing unboundedly.
> Performance optimization: Replace actor channel by unbounded channel

- dds/src/dds_async/data_writer.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/rtps/messages/submessage_elements.rs
- dds/src/rtps/messages/submessages/data_frag.rs
- dds/src/rtps/writer.rs
- dds/src/rtps/writer_history_cache.rs
- dds/src/rtps/writer_proxy.rs
This PR remove the copying of the data when creating fragmented messages. Instead the fragments are created only when the DataFragSubmessage is generated. This PR also includes the sending of the PID_KEY_HASH parameter to reduce the number of calculations of the InstanceHandle on the reader.
> Performance optimization: Data frag optimization

- dds/Cargo.toml
- dds/benches/benchmark.rs
- dds/examples/best_effort_subscriber.rs
- dds/src/dds/publication/data_writer.rs
- dds/src/dds/publication/data_writer_listener.rs
- dds/src/dds/publication/publisher.rs
- dds/src/dds/subscription/data_reader.rs
- dds/src/dds/subscription/data_reader_listener.rs
- dds/src/dds/subscription/subscriber.rs
- dds/src/dds_async/data_reader.rs
- dds/src/dds_async/data_reader_listener.rs
- dds/src/dds_async/data_writer.rs
- dds/src/dds_async/data_writer_listener.rs
- dds/src/dds_async/publisher.rs
- dds/src/dds_async/subscriber.rs
- dds/src/implementation/actors/any_data_reader_listener.rs
- dds/src/implementation/actors/any_data_writer_listener.rs
- dds/tests/listeners.rs
- dds/tests/write_read_special_types.rs
- dds_derive/Cargo.toml
- dds_gen/Cargo.toml
It was not possible to use a user data type (Foo) that contains borrowed fields for Foo-listeners. To achieve this a lifetime is added to the listener traits (including the async versions). That is an API change, hence the version is increased
> Add lifetime support for foo type in listeners

- dds/Cargo.toml
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/domain_participant_factory_actor.rs
Replace tokio sockets by udp sockets by creating std::thread to listen on the blocking socket. This allows us to remove the "net" feature of tokio
> Replace tokio sockets by udp sockets

- dds/src/data_representation_builtin_endpoints/discovered_reader_data.rs
- dds/src/data_representation_builtin_endpoints/discovered_topic_data.rs
- dds/src/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/src/dds/topic_definition/type_support.rs
- dds/src/dds_async/data_writer.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/rtps/messages/overall_structure.rs
- dds/src/rtps/messages/submessage_elements.rs
- dds/src/rtps/messages/submessages/data.rs
- dds/src/rtps/messages/submessages/data_frag.rs
- dds/src/rtps/writer_history_cache.rs
- dds/tests/reliability_tests.rs
- dds/tests/write_read_samples.rs
- dds/tests/write_read_special_types.rs
- dds_derive/src/derive/dds_serialize_data.rs
- interoperability_tests/cyclone_dds/cyclone_dds_big_data_publisher.c
The data messages were not send correctly if padding was needed in the data submessage element. According to X-Types specification bits must be set in the CDR header representation options. Further the Serialized data fragment addded padding itself, which is actually not the job of the submessage element but rather the job of the Rtps Message itself. This lead to wrong data being sent in case of fragmentation. 
Tests were added to address this and the interoperability test with Cyclone DDS was adjusted to contain padding bits.
> Fix data frag

- .github/workflows/python_docs.yml
- dds/src/data_representation_builtin_endpoints/parameter_id_values.rs
- dds/src/dds/builtin_topics.rs
- dds/src/dds/infrastructure/qos.rs
- dds/src/dds/infrastructure/qos_policy.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/tests/discovery.rs
Add DataRepresentationQosPolicy to the Data Reader, Data Writer and Topic Qos and make use of it for the discovery process. For now this QoS has no effect on the actual data transmitted on the wire.
> Add DataRepresentationQosPolicy

- bindings/python/src/domain/domain_participant_listener.rs
- bindings/python/src/publication/publisher_listener.rs
- bindings/python/src/subscription/subcriber_listener.rs
- dds/src/dds/domain/domain_participant_listener.rs
- dds/src/dds/publication/data_writer.rs
- dds/src/dds/publication/publisher_listener.rs
- dds/src/dds/subscription/data_reader.rs
- dds/src/dds/subscription/subscriber_listener.rs
- dds/src/dds_async/domain_participant_listener.rs
- dds/src/dds_async/publisher_listener.rs
- dds/src/dds_async/subscriber_listener.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/src/implementation/actors/subscriber_actor.rs
- dds/tests/listeners.rs
This PR enables using the DataReader and DataWriter functionality on Listeners which do not have the Foo type.
> Allow using Reader and Writer functionality on Listeners without Foo

- dds/src/implementation/runtime/oneshot.rs
This PR fixes a memory leak on the Oneshot channel. The mem forget operation was intended as an optimization to not call Drop however this results in the Arc count not being decreased and the Arc never being de-allocated. This means that every actor operation reply was kept in memory.
> Bugfix: Memory leak on Oneshot channel

- dds/src/dds/topic_definition/type_support.rs
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/payload_serializer_deserializer/cdr_deserializer.rs
- dds/src/implementation/payload_serializer_deserializer/parameter_list_deserializer.rs
- omg_interoperability_executable/src/main.rs
Add interpretation for appendable and plain  XCDR2 types in subscription. This ensures interoperability with Connext DDS, see https://github.com/s2e-systems/dust-dds/actions/runs/10373864841
> Add xcdr2 support

- dds/src/implementation/actors/data_reader_actor.rs
- dds/tests/write_read_samples.rs
Add the functionality of the writer losing ownership of an instance either when deadline is missed or the sample is explicitly unregistered by a writer.
> Add loss of ownership after unregistering and deadline missed

- .circleci/continue-config.yml
- .github/workflows/interoperability.yml
- dds/Cargo.toml
- dds/src/implementation/actors/domain_participant_factory_actor.rs
Add hello world example execution for macos and windows to the pull request pipeline. 
The hello world exampled failed on macos. This is fixed here with the reuse_port option for the socket.
> Add hello world platform tests

- .github/workflows/interoperability.yml
- omg_interoperability_executable/Cargo.toml
- omg_interoperability_executable/build.rs
- omg_interoperability_executable/shape.idl
- omg_interoperability_executable/src/main.rs
Add interoperability executable to artifacts such that it can be downloaded to be put to the OMG-RTPS repo.
Add also ShapeType from idl generation as is done on the omg-rtps repo.
Example actions run: https://github.com/s2e-systems/dust-dds/actions/runs/10635177575
> Add interoperability executable to artifacts

- .github/workflows/interoperability.yml
- Produce an executable that keeps the execution permission flag.
- Rename the executable with the version in its name (as omg-rtps requires it)
Actions run:
https://github.com/s2e-systems/dust-dds/actions/runs/10717421940/job/29717088048
> Fix interoperability executable

- dds/src/xtypes/xcdr_serializer.rs
- Use extend collection for Xcdr2serializers. 
- Make Virtual serializers pub
- Use vecs directly in tests
> Make Xcdr2serializer extend

- dds/src/xtypes/xcdr_serializer.rs
Replace virtual serializer by counter to avoid mismatch in counting the bytes resulting from the serialization
> Replace virtual serializer by counter

- dds/src/xtypes/serialize.rs
- dds/src/xtypes/xcdr_serializer.rs
Use a custom Write trait instead of Extend. This allows custom implementation of Write for example slices while Extend only allows writing of 1 byte at a time
> Use a custom Write trait instead of Extend

- dds/src/rtps/behavior_types.rs
- dds/src/rtps/stateful_writer.rs
The hearbeat period timing was wrong because of using a fraction as a value in nanosec. This result in heartbeat messages being sent roughly every 48ms instead of the intended 200ms. This PR fixes the issue
> Fix heartbeat period timing

- bindings/python/Cargo.toml
- dds/Cargo.toml
- dds_derive/Cargo.toml
- dds_gen/Cargo.toml
- dds_gen/src/lib.rs
- dds_gen/src/preprocessor/mod.rs
- dds_gen/src/preprocessor/test_resources/simple_struct.idl
- dds_gen/tests/basic_types.idl
- dds_gen/tests/basic_types.rs
- dds_gen/tests/enums.idl
- dds_gen/tests/i11eperf.idl
- dds_gen/tests/i11eperf.rs
- dds_gen/tests/module_generation.idl
- dds_gen/tests/nested_types.idl
- dds_gen/tests/structs.rs
- dds_gen/tests/structs_generation.idl
- dds_gen/tests/template_types.idl
- interoperability_tests/build.rs
- omg_interoperability_executable/build.rs
- shapes_demo/build.rs
Add an idlgen preprocessor without added functionality. This is the preparatory step to add support for #include, #define and other preprocessor tags
> Add an idlgen preprocessor without added functionality

- dds/tests/write_read_special_types.rs
- dds_derive/src/derive/type_support.rs
Using `#[derive(DdsType)]` on a type like `struct ArrayContainingType([u8; ARRAY_LENGTH]);` led to a compile error in `get_type_identifier`. The problem is that the member `array_bound_seq` of  `PlainArraySElemDefn` and `PlainArrayLElemDefn` is of type `u8` or `u32`, respectively. When using an actual integer to define the arrays size, the integer expression is used in the proc macro and the compiler happily casts (?) it to the right integer type. But when using a `usize` constant, the constant expression is put into the `vec![...]` call and the compiler fails, as it expects a smaller integer type.
This patch adds proper casts to handle this situation as well as a compile time test case.
> Fix a compile error when using a constant to define an array's size

- .circleci/continue-config.yml
- dds/src/implementation/domain_participant_backend/services/discovery_service.rs
Use reader requested reliability/durability instead of writer offered for matched writer proxies. This fixes a bug in which a best effort reader, which is correctly matched with a reliable writer was behaving a reliable data writer, whereas the writer was behaving as a best effort writer. This mismatch caused problems whenever messages were dropped since no further data would be received after that point.
> Bugfix: Use reader requested reliability/durability instead of writer offered for matched writer proxies

- shapes_demo/src/app.rs
The reliable reader in the Shapes Demo had the DestinationOrderQosPolicyKind set to BySourceTimestamp while the reliable writer was left default. This lead to non matching reader and writer.
To fix this the DestinationOrderQosPolicyKind set to BySourceTimestamp also on the writer side.
> Fix Shapes Demo reliable

- .circleci/config.yml
- dds/src/implementation/domain_participant_backend/entities/data_reader.rs
- dds/src/implementation/domain_participant_backend/entities/data_writer.rs
- dds/src/implementation/domain_participant_backend/entities/domain_participant.rs
- dds/src/implementation/domain_participant_factory/domain_participant_factory_actor.rs
This is a refactor removing the Hash related types from the entities. After this change only the DataReader entity will contain hash maps.
> Refactor: Remove hash types from entities
