- dds/src/implementation/rtps/reader.rs
Add correct generation_rank, absolute_generation_rank and sample_rank information to the sample info.
> DDS-193 Add sample info generation rank and sample rank

- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/subscription/data_reader.rs
- dds/src/subscription/subscriber.rs
- dds/tests/discovery.rs
This PR adds the announcing and processing of user defined data reader deletion.
> DDS-200 Announce deletion of data readers

- dds/src/implementation/data_representation_builtin_endpoints/discovered_reader_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/src/implementation/dds_impl/builtin_publisher.rs
- dds/src/implementation/dds_impl/builtin_subscriber.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/topic_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/implementation/rtps/types.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/overall_structure.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/entityid.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/guid_prefix.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/vendor_id.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/ack_nack.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/gap.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/heart_beat.rs
- dds/src/infrastructure/instance.rs
- dds/tests/discovery.rs
This cleans some of the GUID types.
> DDS-234 Revert entity kind back to constants

- .gitignore
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/guid_prefix.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/info_destination.rs
impl InfoDestination submessage (de)serialization
> DDS-242 impl InfoDestination submessage

- dds/src/implementation/dds_impl/builtin_stateful_reader.rs
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/message_receiver.rs
- dds/src/implementation/dds_impl/participant_discovery.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/writer_proxy.rs
Send InfoDst submessage together with the AckNack and add its processing by the message receiver.
> DDS-244 Send InfoDst submessage

- dds/src/builtin_topics.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_reader_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_topic_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/rtps/types.rs
- dds/tests/data_reader_listener.rs
This PR adapts the default values to allow interoperability with other DDS implementation (e.g. CycloneDDS).
> DDS-245 Adapt discovery defaults for interoperability

- .circleci/config.yml
- dds/src/implementation/rtps/history_cache.rs
- dds/src/implementation/rtps/messages/submessage_elements.rs
- dds/src/implementation/rtps/reader.rs
- dds/src/implementation/rtps/reader_locator.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/types.rs
- dds/src/implementation/rtps/writer.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/overall_structure.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/sequence_number.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/sequence_number_set.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/ack_nack.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/gap.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/heart_beat.rs
- dds/tests/data_reader_listener.rs
Make SequenceNumber a new type. Consequently also the SequenceNumberSubmessageElement has SequenceNumber  in its fields.
> DDS-234 Make SequenceNumber a new type

- dds/src/domain/domain_participant_factory.rs
- dds/src/implementation/dds_impl/configuration.rs
- dds/src/implementation/rtps_udp_psm/udp_transport.rs
Add possibility of selecting the network interface to the configuration environment variable.
> DDS-246 Add interface to configuration and udp construction

- .circleci/config.yml
- dds/examples/hello_world_publisher.rs
- dds/examples/hello_world_subscriber.rs
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/tests/interoperability/publisher/main.c
- dds/tests/interoperability/subscriber/main.c
Send an INFO_DST submessage together with the heartbeat
> DDS-248 Send INFO_DST with heartbeat

- dds/src/implementation/dds_impl/builtin_stateless_reader.rs
- dds/src/implementation/dds_impl/builtin_stateless_writer.rs
- dds/src/implementation/dds_impl/message_receiver.rs
- dds/src/implementation/rtps/history_cache.rs
- dds/src/implementation/rtps/messages/overall_structure.rs
- dds/src/implementation/rtps/messages/submessage_elements.rs
- dds/src/implementation/rtps/messages/submessages.rs
- dds/src/implementation/rtps/messages/types.rs
- dds/src/implementation/rtps/reader.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/overall_structure.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/rtps_header.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/count.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/entityid.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/fragment_number.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/fragment_number_set.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/guid_prefix.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/protocol_version.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/sequence_number.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/sequence_number_set.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessage_elements/vendor_id.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/ack_nack.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/data.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/gap.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/submessages/heart_beat.rs
Remove some submessgae elements. The rest may follow if this here is approved.
> DDS-251 Remove some submessage elements

- dds/src/implementation/dds_impl/dcps_service.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/tests/discovery.rs
Implement the participant find_topic method and use it for the topic discovery test instead of sleep functions
> DDS-253 Implement participant find_topic method

- dds/examples/best_effort_publisher.rs
- dds/examples/best_effort_subscriber.rs
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/tests/discovery.rs
- Fix not calling on_publication_matched by not keeping a write lock
- Add a sedp condvar notify to increase discovery performance
> DDS-254 Add reader_discovers_disposed_writer_same_participant test

- dds/src/domain/domain_participant.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/publication/publisher.rs
- dds/tests/domain_participant_api.rs
- dds/tests/publisher_api.rs
Add default QoS operations to factory entities where it was missing
> DDS-262 Add default QoS operations

- idlgen/Cargo.toml
- interoperability_tests/Cargo.toml
Fix pest version to avoid build issue introduced in 2.5.4
> Fix pest version

- .gitignore
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/builtin_stateless_writer.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/writer.rs
- dds/tests/write_read_keyed_topic.rs
- interoperability_tests/BigData.idl
- interoperability_tests/CMakeLists.txt
- interoperability_tests/Cargo.toml
- interoperability_tests/build.rs
- interoperability_tests/cyclone_dds_big_data_publisher.c
- interoperability_tests/cyclone_dds_big_data_subscriber.c
- interoperability_tests/dust_dds_big_data_subscriber.rs
Implement the reliable transmission of data fragments
> DDS-275 implement reliable data frag

- .circleci/config.yml
- dds/src/implementation/dds_impl/builtin_publisher.rs
- dds/src/implementation/dds_impl/builtin_subscriber.rs
- dds/src/implementation/dds_impl/message_receiver.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/implementation/rtps/history_cache.rs
- dds/src/implementation/rtps/messages/types.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/writer_proxy.rs
- interoperability_tests/BigData.idl
- interoperability_tests/Cargo.toml
- interoperability_tests/cyclone_dds_big_data_publisher.c
- interoperability_tests/dust_dds_big_data_publisher.rs
- interoperability_tests/dust_dds_big_data_subscriber.rs
Add data fragment interoperability on the publisher side.
> DDS-275 Data frag publisher interoperability

- dds/src/implementation/dds_impl/builtin_publisher.rs
- dds/src/implementation/dds_impl/builtin_stateful_reader.rs
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/builtin_stateless_writer.rs
- dds/src/implementation/dds_impl/builtin_subscriber.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/message_receiver.rs
- dds/src/implementation/dds_impl/participant_discovery.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/implementation/rtps/messages/mod.rs
- dds/src/implementation/rtps/messages/overall_structure.rs
- dds/src/implementation/rtps/reader_locator.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/stateless_writer.rs
- dds/src/implementation/rtps/transport.rs
- dds/src/implementation/rtps/utils/clock.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/implementation/rtps_udp_psm/mapping_rtps_messages/overall_structure.rs
- dds/src/implementation/rtps_udp_psm/udp_transport.rs
Refactor the message sending as preparation to be able to send single fragments
> DDS-281 Refactor message sending

- dds/Cargo.toml
- dds/src/domain/domain_participant_factory.rs
- dds/src/implementation/configuration.rs
- dds/src/implementation/configuration_schema_generator.rs
- dds/src/implementation/dds_impl/configuration.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/mod.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/mod.rs
- dds/src/lib.rs
Make fragmentation size configurable through DUST_DDS_CONFIGURATION. Also add a json schema generator.
> DDS-274 Make fragmentation size configurable

- dds/src/implementation/rtps/history_cache.rs
- dds/src/implementation/rtps/reader_proxy.rs
Use one function for unsent_changes and requested_changes.
> DDS-281 Refactor reader proxy

- dds/Cargo.toml
- dds/src/implementation/dds_impl/builtin_publisher.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/tests/discovery.rs
Add PartitionQosPolicy functionality
> DDS-282 Add PartitionQosPolicy functionality

- dds/src/implementation/dds_impl/participant_discovery.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/types.rs
- dds/tests/write_read_keyed_topic.rs
This PR makes the messaging behavior between the reader and the writer follow the Request x Offered principle described in standard, i.e. if a Writer offers Reliable and a Reader requests Best-Effort the communication will follow a best effort structure.
> DDS-296 Add writer/reader negotiated behavior

- dds/src/implementation/dds_impl/builtin_stateful_reader.rs
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/builtin_subscriber.rs
- dds/src/implementation/dds_impl/message_receiver.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/dds_impl/user_defined_subscriber.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/implementation/utils/timer_factory.rs
- dds/tests/discovery.rs
- dds/tests/domain_participant_api.rs
Add processing of Gap submessage.
> DDS-298 Add processing of Gap submessage

- dds/src/implementation/rtps/reader.rs
- dds/src/implementation/rtps/writer.rs
- dds/tests/write_read_samples.rs
This PR adds the handling of WriterDataLifecycleQosPolicy
> DDS-289 Add WriterDataLifecycle qos policy handling

- dds/examples/hello_world_publisher.rs
- dds/examples/hello_world_subscriber.rs
- dds/src/implementation/dds_impl/builtin_stateful_reader.rs
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/builtin_stateless_reader.rs
- dds/src/implementation/dds_impl/builtin_stateless_writer.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_reader.rs
- dds/src/implementation/rtps/reader.rs
- dds/src/implementation/utils/timer_factory.rs
- dds/src/infrastructure/qos.rs
- dds/src/infrastructure/qos_policy.rs
- dds/src/infrastructure/time.rs
- dds/tests/domain_participant_api.rs
- dds/tests/domain_participant_factory.rs
- dds/tests/executables/publisher.rs
- dds/tests/executables/subscriber.rs
- dds/tests/listeners.rs
- dds/tests/write_read_samples.rs
- interoperability_tests/dust_dds_big_data_publisher.rs
- interoperability_tests/dust_dds_big_data_subscriber.rs
- interoperability_tests/dust_dds_publisher.rs
- interoperability_tests/dust_dds_subscriber.rs
- shapes_demo/src/main.rs
- shapes_demo/src/subscriber.rs
Replace the Duration type on the QoS by a DurationKind which allows representing Finite and Infinite duration as variants of an Enum.
> DDS-288 Adjust Duration type in QoS types

- dds/src/implementation/dds_impl/builtin_publisher.rs
- dds/src/implementation/dds_impl/builtin_stateful_writer.rs
- dds/src/implementation/dds_impl/dcps_service.rs
- dds/src/implementation/dds_impl/domain_participant_impl.rs
- dds/src/implementation/dds_impl/user_defined_data_writer.rs
- dds/src/implementation/dds_impl/user_defined_publisher.rs
- dds/src/implementation/rtps/stateful_writer.rs
- dds/src/implementation/rtps/writer.rs
- dds/tests/write_read_samples.rs
Add the usage of LifespanQosPolicy to the writer before sending messages to avoid sending stale data
> DDS-288 Do not send stale data from writer

- shapes_demo/Cargo.toml
- shapes_demo/src/main.rs
- Use a periodic timer to make data writing independent from refresh rate  
- Use a time based rendering of shapes, such that it's velocity does not depend on the refresh rate
> DDS-293 Make velocity stable

- dds/src/implementation/rtps/types.rs
Change S2E vendor ID to match listing from OMG:
https://www.dds-foundation.org/dds-rtps-vendor-and-product-ids/
> DDS-257 Change S2E vendor id

- .circleci/config.yml
- .github/workflows/main.yml
- README.md
- dds/Cargo.toml
- dds/src/domain/domain_participant_factory.rs
- dds/src/implementation/configuration.rs
- dds/src/implementation/configuration_schema_generator.rs
- dds/src/infrastructure/qos_policy.rs
- dds/src/lib.rs
- dds_derive/Cargo.toml
- interoperability_tests/Cargo.toml
- shapes_demo/Cargo.toml
Update package to version 0.2 and prepare files for release
> Update to version 0.2.0

- dds/src/domain/domain_participant.rs
- dds/src/implementation/dds_impl/node_user_defined_publisher.rs
- dds/src/implementation/dds_impl/node_user_defined_subscriber.rs
- dds/src/publication/data_writer.rs
- dds/src/subscription/data_reader.rs
- dds/src/topic_definition/topic.rs
Remove obsolete commented out drop code
> DDS-305 Remove commented out code

- dds/Cargo.toml
> Step up to 0.2.1

- dds/Cargo.toml
- dds_derive/Cargo.toml
Change version also in dust_dds_derive in toml file
> Release 0.2.1

- dds/src/dds/domain/domain_participant_factory.rs
This changes updates the creation of the GUID prefix to use a Host ID, App ID and Instance ID. The instance ID is created by incrementing an atomic counter to guarantee that each new participant gets a new number.
> DDS-327 Create guid prefix without port info

- dds/src/implementation/utils/actor.rs
- dds/src/implementation/utils/mod.rs
Add scaffolding for implementing the Actor
> DDS-329 Add scaffolding for implementing the Actor

- dds/src/implementation/dds/dds_data_writer.rs
- dds/src/implementation/rtps/messages/submessage_elements.rs
- dds/src/implementation/rtps/messages/submessages/ack_nack.rs
- dds/src/implementation/rtps/messages/submessages/gap.rs
- dds/src/implementation/rtps/reader_locator.rs
- dds/src/implementation/rtps/stateful_reader.rs
- dds/src/implementation/rtps/types.rs
- dds/src/implementation/rtps/writer_proxy.rs
Make gap messages possible to send gaps bigger then 256 unsent changes
> Check SequenceNumberSet validity

- dds/src/implementation/rtps/messages/submessage_elements.rs
- dds/src/implementation/rtps/messages/submessages/nack_frag.rs
- dds/src/implementation/rtps/writer_proxy.rs
Adds validity check on FragmentNumberSet construction
> DDS-341 Remove pubs from FragmentNumberSet

- dds/src/implementation/dds/dds_data_reader.rs
- dds/src/implementation/dds/dds_data_reader_listener.rs
- dds/src/implementation/dds/dds_domain_participant_listener.rs
- dds/src/implementation/dds/dds_subscriber_listener.rs
Implement sample lost callback and status condition.
> DDS-352 Implement sample lost callback and status condition

- dds/src/dds/publication/data_writer.rs
- dds/tests/publisher_api.rs
- dds/tests/subscriber_api.rs
Add get_topic functionality to DataWriter
> DDS-360 Add writer get_topic functionality

- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/rtps/messages/overall_structure.rs
- dds/src/implementation/rtps/messages/submessage_elements.rs
- dds/src/implementation/rtps/messages/submessages/ack_nack.rs
- dds/src/implementation/rtps/messages/submessages/data.rs
- dds/src/implementation/rtps/messages/submessages/data_frag.rs
- dds/src/implementation/rtps/messages/submessages/gap.rs
- dds/src/implementation/rtps/messages/submessages/heartbeat.rs
- dds/src/implementation/rtps/messages/submessages/heartbeat_frag.rs
- dds/src/implementation/rtps/messages/submessages/info_destination.rs
- dds/src/implementation/rtps/messages/submessages/info_reply.rs
- dds/src/implementation/rtps/messages/submessages/info_source.rs
- dds/src/implementation/rtps/messages/submessages/info_timestamp.rs
- dds/src/implementation/rtps/messages/submessages/nack_frag.rs
- dds/src/implementation/rtps/messages/submessages/pad.rs
- dds/src/implementation/rtps/reader_proxy.rs
- dds/src/implementation/rtps/types.rs
- dds/src/implementation/rtps/writer_history_cache.rs
- dds/src/implementation/rtps/writer_proxy.rs
- dds/src/implementation/rtps_udp_psm/udp_transport.rs
This PR optimizes the memory usage on the DDS Data writer side by removing Vec allocations in the submessage elements and submessages.
> Performance: Writer side memory usage optimization

- .circleci/continue-config.yml
- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/rtps/messages/submessages/data.rs
- interoperability_tests/Cargo.toml
- interoperability_tests/DisposeData.idl
- interoperability_tests/build.rs
- interoperability_tests/cyclone_dds/CMakeLists.txt
- interoperability_tests/cyclone_dds/cyclone_dds_publisher_dispose.c
- interoperability_tests/cyclone_dds/cyclone_dds_subscriber_dispose.c
- interoperability_tests/dust_dds_publisher_dispose.rs
- interoperability_tests/dust_dds_subscriber_dispose.rs
- interoperability_tests/fast_dds/CMakeLists.txt
- interoperability_tests/fast_dds/fast_dds_publisher_dispose.cpp
- interoperability_tests/fast_dds/fast_dds_subscriber_dispose.cpp
- shapes_demo/src/app.rs
Fix interoperability of disposing sample and add tests.
> Interoperability for disposing samples

- dds/src/implementation/actors/data_reader_actor.rs
- dds/src/implementation/payload_serializer_deserializer/cdr_deserializer.rs
- dds/src/implementation/rtps/messages/types.rs
- dds/tests/write_read_samples.rs
This changes fixes some rounding errors when converting between RTPS and DDS times
> Fix RTPS to DDS time conversion issues

- shapes_demo/Cargo.toml
Use a fixed version of egui_extras
> Fix Shapes Demo compilation

- dds/README.md
> Minor fix to README sections

- dds/Cargo.toml
- dds/src/dds_async/data_reader.rs
- dds/src/dds_async/data_writer.rs
- dds/src/dds_async/domain_participant.rs
- dds/src/dds_async/publisher.rs
- dds/src/dds_async/subscriber.rs
- dds/src/dds_async/topic.rs
- dds/src/dds_async/wait_set.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/domain_participant_factory_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/src/implementation/actors/subscriber_actor.rs
- dds/src/implementation/actors/topic_actor.rs
- dds/src/implementation/rtps/writer.rs
This PR is just a refactor and reduction of the number of actor interface methods mostly on the domain participant.
> Domain participant actor cleanup

- shapes_demo/src/app.rs
- shapes_demo/src/main.rs
- shapes_demo/src/shapes_widget.rs
- Fix double topic creation error
- Adds a delete button for the reader and writer
- Add fixed history of 6 for the reader and visualize the history by adding transparency
> Add delete button

- shapes_demo/src/app.rs
- shapes_demo/src/shapes_widget.rs
Add unrigister and dispose buttons. Also visualize disposed and unregistered shapes.
> Add unregistering and dispose buttons

- dds/tests/write_read_special_types.rs
- dds_derive/src/derive/dds_type_xml.rs
Add support and test for nested DDS types
> 277 ddstype derivation macro support for nested types

- dds/src/data_representation_builtin_endpoints/parameter_id_values.rs
- dds/src/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/src/dds/infrastructure/instance.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/tests/write_read_samples.rs
- telescope/src/main.rs
Add discovered participants to SPDP data
> Add discovered participants to SPDP

- .circleci/continue-config.yml
- telescope/src/main.rs
Fix the telescope and add it's compilation check to circle CI. Also harmonize the rust version of the shapes demo
> Add telescope compilation check to CI

- .circleci/continue-config.yml
- interoperability_tests/Cargo.toml
- interoperability_tests/NestedType.idl
- interoperability_tests/build.rs
- interoperability_tests/cyclone_dds/CMakeLists.txt
- interoperability_tests/cyclone_dds/cyclone_dds_publisher_nested.c
- interoperability_tests/cyclone_dds/cyclone_dds_subscriber_nested.c
- interoperability_tests/dust_dds_publisher_nested.rs
- interoperability_tests/dust_dds_subscriber_nested.rs
Add an interoperability test between Cyclone DDS and Dust DDS for nested types
> 292 cyclone interoperability with data types

- bindings/python/Cargo.toml
- dds/Cargo.toml
- dds_derive/Cargo.toml
- dds_gen/Cargo.toml
> Update to version 0.10.1

- .circleci/continue-config.yml
- Cargo.toml
- bindings/python/build.rs
- bindings/python/src/infrastructure/qos.rs
- bindings/python/src/infrastructure/qos_policy.rs
Fix missing QoS mapping on Python bindings. Add the bindings to the default workspace to prevent breaking the code in the future.
> Fix python bindings

- dds/src/dds_async/data_writer.rs
- dds/src/implementation/actors/any_data_writer_listener.rs
- dds/src/implementation/actors/data_writer_actor.rs
- dds/src/implementation/actors/domain_participant_actor.rs
- dds/src/implementation/actors/publisher_actor.rs
- dds/tests/listeners.rs
Add detection of OfferedDeadlineMissed status to trigger the listener and wait set
> Add OfferedDeadlineMissed status detection

- bindings/python/Cargo.toml
- dds/Cargo.toml
- dds_derive/Cargo.toml
- dds_gen/Cargo.toml
> Update to version 0.11

- dds/src/xtypes/xcdr_serializer.rs
- dds/tests/domain_participant_api.rs
Fix issue with byte counter usage
> Fix issue with byte counter usage

- dds/src/dds/topic_definition/type_support.rs
- dds/src/implementation/data_representation_builtin_endpoints/payload_serializer_deserializer/parameter_list_deserializer.rs
- dds/src/implementation/data_representation_builtin_endpoints/payload_serializer_deserializer/parameter_list_serializer.rs
- dds/src/xtypes/xcdr_deserializer.rs
Add pre-allocation for DdsSerialize and the buildin ParameterList serializer.
> Simplify parameterlist serde

- dds/src/implementation/xtypes_glue/key_and_instance_handle.rs
Add support for CDR2 on key deserializers
> Add support for CDR2 on key deserializers

- .circleci/Dockerfile
- .circleci/android/Dockerfile
- .circleci/continue-config.yml
- dds/src/rtps/stateful_reader.rs
- dds/src/rtps/writer_proxy.rs
Remove pub fields from RtpsWriterProxy
> Refactor: Remove pub fields from RtpsWriterProxy

- dds_gen/Cargo.toml
- dds_gen/src/preprocessor/mod.rs
- dds_gen/src/preprocessor/test_resources/file_included.idl
- dds_gen/src/preprocessor/test_resources/file_with_include.idl
Add the #include functionality to the preprocessor of the idlgen
> Idlgen preprocessor include pragma

- dds_gen/src/lib.rs
- dds_gen/src/preprocessor/mod.rs
- dds_gen/src/preprocessor/test_resources/file_with_define.idl
Add the #define directive to the idlgen preprocessor
> Idlgen preprocessor define directive

- dds_gen/src/lib.rs
- dds_gen/src/preprocessor/mod.rs
- dds_gen/src/preprocessor/preprocessor_grammar.pest
- dds_gen/src/preprocessor/test_resources/file_with_ifdef.idl
- dds_gen/src/preprocessor/test_resources/file_with_ifdef_not_defined.idl
- dds_gen/src/preprocessor/test_resources/file_with_ifndef.idl
- dds_gen/src/preprocessor/test_resources/file_with_ifndef_defined.idl
Add support for the #ifdef and #ifndef preprocessor directives to the idlgen.
> Add Idlgen ifdef and ifndef support

- dds/examples/configuration.rs
- dds/examples/rtps_transport_configuration.rs
- dds/src/dds/configuration.rs
- dds/src/dds/domain/domain_participant_factory.rs
- dds/src/dds_async/domain_participant_factory.rs
- dds/src/implementation/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/implementation/data_representation_builtin_endpoints/parameter_id_values.rs
- dds/src/implementation/domain_participant_backend/domain_participant_actor.rs
- dds/src/implementation/domain_participant_backend/services/discovery_service.rs
- dds/src/implementation/domain_participant_backend/services/publisher_service.rs
- dds/src/implementation/domain_participant_factory/domain_participant_factory_actor.rs
- dds/src/rtps/factory.rs
- dds/src/rtps/mod.rs
- dds/src/rtps/stateful_reader.rs
- dds/src/rtps/transport.rs
- dds/src/rtps/writer_proxy.rs
- dds/src/transport/factory.rs
- dds/src/transport/mod.rs
- dds/src/transport/participant.rs
- dds/src/transport/reader.rs
Add a configurable transport which opens the possibilities of using custom transports for DDS
> Add configurable transport

- .circleci/Dockerfile
- .circleci/android/Dockerfile
- .circleci/continue-config.yml
- CONTRIBUTING.md
- bindings/python/build.rs
- dds/src/dds/domain/domain_participant.rs
- dds/src/dds/publication/data_writer_listener.rs
- dds/src/dds/subscription/data_reader_listener.rs
- dds/src/implementation/domain_participant_backend/entities/data_reader.rs
- dds/src/implementation/xtypes_glue/key_and_instance_handle.rs
- dds/src/rtps/behavior_types.rs
- dds/src/rtps/messages/submessage_elements.rs
- dds/src/rtps/messages/types.rs
- dds/src/rtps/types.rs
- dds/src/xtypes/xcdr_serializer.rs
- shapes_demo/Cargo.toml
Add contribution guidelines in preparation to accepting external PRs for Dust DDS.
Since the build is broken due to dependencies of shapes demo, this is also fixed as part of the PR.
> Add contribution guidelines

- dds/src/dds_async/condition.rs
- dds/src/dds_async/data_reader.rs
- dds/src/dds_async/data_writer.rs
- dds/src/dds_async/domain_participant.rs
- dds/src/dds_async/domain_participant_factory.rs
- dds/src/dds_async/publisher.rs
- dds/src/dds_async/subscriber.rs
- dds/src/dds_async/topic.rs
- dds/src/implementation/domain_participant_backend/services/data_reader_service.rs
- dds/src/implementation/domain_participant_backend/services/data_writer_service.rs
- dds/src/implementation/domain_participant_backend/services/discovery_service.rs
- dds/src/implementation/domain_participant_backend/services/domain_participant_service.rs
- dds/src/implementation/domain_participant_backend/services/event_service.rs
- dds/src/implementation/domain_participant_backend/services/message_service.rs
- dds/src/implementation/domain_participant_backend/services/publisher_service.rs
- dds/src/implementation/domain_participant_backend/services/subscriber_service.rs
- dds/src/implementation/domain_participant_backend/services/topic_service.rs
- dds/src/implementation/domain_participant_factory/domain_participant_factory_actor.rs
- dds/src/implementation/listeners/data_reader_listener.rs
- dds/src/implementation/listeners/data_writer_listener.rs
- dds/src/implementation/listeners/domain_participant_listener.rs
- dds/src/implementation/listeners/publisher_listener.rs
- dds/src/implementation/listeners/subscriber_listener.rs
- dds/src/implementation/status_condition/status_condition_actor.rs
- dds/src/runtime/actor.rs
- dds/src/runtime/oneshot.rs
This PR removes the always included reply from the actor to simplify the framework. It is a pure refactor with no impact on external usage or API
> Refactor: Remove actor always included reply

- dds/src/rtps/message_creator.rs
- dds/src/rtps/stateful_writer.rs
- dds/src/rtps/stateless_writer.rs
- dds/src/rtps/writer_proxy.rs
- dds/src/rtps_messages/overall_structure.rs
- dds/tests/reliability_tests.rs
Remove Box allocations on RTPS message writing
> Remove RTPS message writing heap allocations

- dds/Cargo.toml
- dds/src/dcps/domain_participant_actor.rs
- dds/tests/discovery.rs
- omg_interoperability_executable/Cargo.toml
- omg_interoperability_executable/src/main.rs
- Add back partition matching on base of fnmatch. 
- Update OMG interoperability test program such that partition tests are passing
> Add partition matching 

- dds_derive/src/derive/dds_serialize_data.rs
- dds_derive/src/derive/type_support.rs
- dds_derive/src/derive/xtypes.rs
> feat: add #[automatically_derived] in derived impl

- bindings/python/src/topic_definition/type_support.rs
- dds/src/dcps/data_representation_builtin_endpoints/discovered_reader_data.rs
- dds/src/dcps/data_representation_builtin_endpoints/discovered_topic_data.rs
- dds/src/dcps/data_representation_builtin_endpoints/discovered_writer_data.rs
- dds/src/dcps/data_representation_builtin_endpoints/spdp_discovered_participant_data.rs
- dds/src/dcps/infrastructure/qos_policy.rs
- dds/src/dcps/infrastructure/time.rs
- dds/src/dcps/infrastructure/type_support.rs
- dds_derive/src/derive/type_support.rs
Add placeholder for create_sample function to TypeSupport
> Add placeholder for create_sample function to TypeSupport
